backend:
  name: git-gateway
  branch: main

site_url: https://lionex.org

publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "images/uploads"
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Get Connected"
        name: "get-connected"
        file: "content/services/get_connected.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Publish Date", name: date, widget: datetime }
          - {label: Draft, name: draft, widget: boolean}
          - {label: Featured, name: featured, widget: boolean}
          - {label: Weight, name: weight, widget: number}
          - {label: Body, name: body, widget: markdown}

